#!/bin/bash

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  ibmcloud ce job delete -n job-engine -f --inf
  # ibmcloud ce jobrun delete -n job-engine-instance  -f  --ignore--not-found
}

set -ex

echo "Login to IBM Cloud..."
ibmcloud login -r ${REGION} --apikey ${API_KEY}
ibmcloud target -g ${RESOURCE_GROUP}
ibmcloud ce project select --name ${PROJECT_GROUP}

clean
# [[ "$1" == "clean" ]] && exit 0

# Create a Job definition
ibmcloud ce job create --name job-engine --image ${REGISTRY}/firstjob:latest --registry-secret=${REGISTRY_SECRET} \
  --env region=${REGION} --env resource-group=${RESOURCE_GROUP}

# Now submit the job using that definition
ibmcloud ce jobrun submit --name job-engine-instance --job job-engine