#!/bin/bash

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  ibmcloud ce job delete -n job-engine -f --inf
  # ibmcloud ce jobrun delete -n job-engine-instance  -f  --ignore--not-found
}

set -ex

export REGISTRY=de.icr.io/codeengine-job
export REGION=eu-de
export API_KEY=Ld9beQpCK8lKLzvNXXiS0g9ODhGr0tGT55slBW5UIDg_
export RESOURCE_GROUP=Default
export REGISTRY_SECRET=ce-default-icr-eu-de

echo "Login to IBM Cloud..."
ibmcloud login -r ${REGION} --apikey ${API_KEY}
ibmcloud target -g ${RESOURCE_GROUP}
ibmcloud ce project select --id ceed57da-f34d-4980-b360-d8cabb6d6b2e

clean
# [[ "$1" == "clean" ]] && exit 0

# Create a Job definition
ibmcloud ce job create --name job-engine --image ${REGISTRY}/firstjob:latest --registry-secret=${REGISTRY_SECRET}

# Now submit the job using that definition
ibmcloud ce jobrun submit --name job-engine-instance --job job-engine